delay:
  action: -0
  observation: -0
frequnecy: 
  frameskip_custom: 32
  freq: 62.5
target_vel:
  x: 0.5
result:
  sim: /home/dyros/tocabi_ws/src/tocabi_cc/result/code_test/data_4.csv
  real: /home/dyros/catkin_ws/data_